[build]
  command = "npm run build"
  publish = "."
  node_version = "18"

[[redirects]]
  from = "/*"
  status = 200
  to = "/index.html"
  force = true

/static/css/* 
  Cache-Control: public, max-age=31536000
